# Fix time zone issues
Apple saved all of my data in my current time zone, but I lived in China for most of the time of this data. I will explore how to change the timezones for the time periods I was in China.

In [1]:
import pandas as pd
import datetime as dt
import matplotlib.pyplot as plt

Helpful resource: https://www.python-engineer.com/posts/apple-health-data-python/

In [2]:
records_list = pd.read_csv('records_list.csv')

/var/folders/hj/mq308hhs3rz5q1mbkdf0261m0000gn/T/ipykernel_33013/4276935878.py:1: DtypeWarning: Columns (3,7) have mixed types. Specify dtype option on import or set low_memory=False.
  records_list = pd.read_csv('records_list.csv')

In [3]:
records_list

,creation_time,activity_type,source,source_ver,unit_of_measure,activity_start_time,activity_end_time,value,device
0,2015-10-10 06:27:26-06:00,DistanceWalkingRunning,Marky Doug,9.0.2,km,2015-10-10 04:48:17 -0600,2015-10-10 04:54:17 -0600,0.00144,"<<HKDevice: 0x2833bde00>, name:iPhone, manufac..."
1,2015-10-10 06:27:26-06:00,StepCount,Marky Doug,9.0.2,count,2015-10-10 02:46:48 -0600,2015-10-10 02:51:50 -0600,569.0,"<<HKDevice: 0x2833aa8a0>, name:iPhone, manufac..."
2,2015-10-10 06:27:26-06:00,StepCount,Marky Doug,9.0.2,count,2015-10-10 02:51:50 -0600,2015-10-10 02:54:35 -0600,135.0,"<<HKDevice: 0x2833aa8a0>, name:iPhone, manufac..."
3,2015-10-10 06:27:26-06:00,StepCount,Marky Doug,9.0.2,count,2015-10-10 03:09:06 -0600,2015-10-10 03:14:07 -0600,436.0,"<<HKDevice: 0x2833aa8a0>, name:iPhone, manufac..."
4,2015-10-10 06:27:26-06:00,StepCount,Marky Doug,9.0.2,count,2015-10-10 03:14:07 -0600,2015-10-10 03:19:07 -0600,569.0,"<<HKDevice: 0x2833aa8a0>, name:iPhone, manufac..."
...,...,...,...,...,...,...,...,...,...
2267585,2022-12-08 12:39:50-06:00,ActiveEnergyBurned,Mark的Apple Watch,9.1,Cal,2022-12-08 12:30:39 -0600,2022-12-08 12:30:49 -0600,0.076,"<<HKDevice: 0x2833b8e10>, name:Apple Watch, ma..."
2267586,2022-12-08 12:39:50-06:00,ActiveEnergyBurned,Mark的Apple Watch,9.1,Cal,2022-12-08 12:29:38 -0600,2022-12-08 12:30:39 -0600,1.673,"<<HKDevice: 0x2833b8e10>, name:Apple Watch, ma..."
2267587,2022-12-08 12:39:51-06:00,AppleExerciseTime,Mark的Apple Watch,9.1,min,2022-12-08 12:29:00 -0600,2022-12-08 12:30:00 -0600,1,"<<HKDevice: 0x2833b9fe0>, name:Apple Watch, ma..."
2267588,2022-12-08 12:40:35-06:00,ActiveEnergyBurned,Mark的Apple Watch,9.1,Cal,2022-12-08 12:39:53 -0600,2022-12-08 12:40:13 -0600,0.121,"<<HKDevice: 0x2833b8e10>, name:Apple Watch, ma..."
2267589,2022-12-08 12:40:35-06:00,ActiveEnergyBurned,Mark的Apple Watch,9.1,Cal,2022-12-08 12:38:51 -0600,2022-12-08 12:39:32 -0600,0.19,"<<HKDevice: 0x2833b8e10>, name:Apple Watch, ma..."

### Deal with time zones. It will take a long time.

Going through my photos for the time period I have Apple health data for. I will separate dataframes it into periods  of time, then convert the timezone of those times while I was in China.

In [4]:
records_list['creation_time'] = pd.to_datetime(records_list['creation_time'])

In [5]:
records_list = records_list.set_index('creation_time').sort_index()

In [6]:
china1 = records_list[:'2016-11-21 11']

In [7]:
china1.tail()

,activity_type,source,source_ver,unit_of_measure,activity_start_time,activity_end_time,value,device
creation_time,,,,,,,,
2016-11-21 09:26:32-06:00,StepCount,Marky Doug,10.1.1,count,2016-11-21 09:25:20 -0600,2016-11-21 09:25:43 -0600,13,"<<HKDevice: 0x2833aeee0>, name:iPhone, manufac..."
2016-11-21 09:29:42-06:00,StepCount,Marky Doug,10.1.1,count,2016-11-21 09:28:36 -0600,2016-11-21 09:29:36 -0600,119,"<<HKDevice: 0x2833aeee0>, name:iPhone, manufac..."
2016-11-21 09:30:50-06:00,StepCount,Marky Doug,10.1.1,count,2016-11-21 09:29:36 -0600,2016-11-21 09:30:09 -0600,29,"<<HKDevice: 0x2833aeee0>, name:iPhone, manufac..."
2016-11-21 10:25:38-06:00,DistanceWalkingRunning,Marky Doug,10.1.1,km,2016-11-21 09:19:20 -0600,2016-11-21 09:29:19 -0600,0.08624,"<<HKDevice: 0x283394be0>, name:iPhone, manufac..."
2016-11-21 10:25:38-06:00,DistanceWalkingRunning,Marky Doug,10.1.1,km,2016-11-21 09:29:19 -0600,2016-11-21 09:30:09 -0600,0.04671,"<<HKDevice: 0x283394be0>, name:iPhone, manufac..."

In [8]:
china1.shape

(81607, 8)

In [9]:
def change_time_zone(df):
    #convert index timezone
    df = df.tz_convert('Asia/Chongqing')
    #convert activity_start_time timezone
    df['activity_start_time'] = pd.to_datetime(df['activity_start_time']).dt.tz_convert('Asia/Chongqing')
    #convert activity_end_time timezone
    df['activity_end_time'] = pd.to_datetime(df['activity_end_time']).dt.tz_convert('Asia/Chongqing')
    return df

In [10]:
us1 = records_list['2016-11-21 20':'2017-01-12 17']

In [12]:
china2 = records_list['2017-01-12 17':'2017-05-01 08']

In [13]:
china2.tail()

,activity_type,source,source_ver,unit_of_measure,activity_start_time,activity_end_time,value,device
creation_time,,,,,,,,
2017-05-01 06:33:04-06:00,DistanceWalkingRunning,Marky Doug,10.3.1,km,2017-05-01 06:11:47 -0600,2017-05-01 06:20:52 -0600,0.14759,"<<HKDevice: 0x28335b160>, name:iPhone, manufac..."
2017-05-01 06:49:18-06:00,StepCount,Marky Doug,10.3.1,count,2017-05-01 06:46:19 -0600,2017-05-01 06:48:45 -0600,46,"<<HKDevice: 0x2833aea30>, name:iPhone, manufac..."
2017-05-01 06:49:18-06:00,StepCount,Marky Doug,10.3.1,count,2017-05-01 06:44:16 -0600,2017-05-01 06:45:17 -0600,48,"<<HKDevice: 0x2833aea30>, name:iPhone, manufac..."
2017-05-01 06:49:18-06:00,StepCount,Marky Doug,10.3.1,count,2017-05-01 06:39:21 -0600,2017-05-01 06:41:37 -0600,37,"<<HKDevice: 0x2833aea30>, name:iPhone, manufac..."
2017-05-01 06:49:18-06:00,StepCount,Marky Doug,10.3.1,count,2017-05-01 06:45:17 -0600,2017-05-01 06:46:19 -0600,63,"<<HKDevice: 0x2833aea30>, name:iPhone, manufac..."

In [14]:
us2 = records_list['2017-05-01 08':'2017-06-06 01']

In [15]:
us2.head()

,activity_type,source,source_ver,unit_of_measure,activity_start_time,activity_end_time,value,device
creation_time,,,,,,,,
2017-05-01 20:01:39-06:00,StepCount,Marky Doug,10.3.1,count,2017-05-01 19:34:31 -0600,2017-05-01 19:37:05 -0600,28,"<<HKDevice: 0x2833aea30>, name:iPhone, manufac..."
2017-05-01 20:01:39-06:00,StepCount,Marky Doug,10.3.1,count,2017-05-01 19:37:05 -0600,2017-05-01 19:37:08 -0600,14,"<<HKDevice: 0x2833aea30>, name:iPhone, manufac..."
2017-05-01 20:21:44-06:00,DistanceWalkingRunning,Marky Doug,10.3.1,km,2017-05-01 06:41:37 -0600,2017-05-01 06:48:45 -0600,0.10946,"<<HKDevice: 0x28335b160>, name:iPhone, manufac..."
2017-05-01 20:21:44-06:00,DistanceWalkingRunning,Marky Doug,10.3.1,km,2017-05-01 19:27:17 -0600,2017-05-01 19:37:08 -0600,0.02882,"<<HKDevice: 0x28335b160>, name:iPhone, manufac..."
2017-05-01 20:21:44-06:00,DistanceWalkingRunning,Marky Doug,10.3.1,km,2017-05-01 06:33:21 -0600,2017-05-01 06:41:37 -0600,0.02498,"<<HKDevice: 0x28335b160>, name:iPhone, manufac..."

In [16]:
china3 = records_list['2017-06-06 01':'2018-07-11 12']

In [17]:
china3.tail()

,activity_type,source,source_ver,unit_of_measure,activity_start_time,activity_end_time,value,device
creation_time,,,,,,,,
2018-07-11 08:54:58-06:00,DistanceWalkingRunning,Marky Doug,11.4,km,2018-07-11 07:45:44 -0600,2018-07-11 07:55:14 -0600,0.04199,"<<HKDevice: 0x2833b9a40>, name:iPhone, manufac..."
2018-07-11 08:54:58-06:00,DistanceWalkingRunning,Marky Doug,11.4,km,2018-07-11 07:07:34 -0600,2018-07-11 07:13:48 -0600,0.13802,"<<HKDevice: 0x2833b9a40>, name:iPhone, manufac..."
2018-07-11 08:54:58-06:00,DistanceWalkingRunning,Marky Doug,11.4,km,2018-07-11 07:01:00 -0600,2018-07-11 07:07:34 -0600,0.00973,"<<HKDevice: 0x2833b9a40>, name:iPhone, manufac..."
2018-07-11 09:20:21-06:00,StepCount,Marky Doug,11.4,count,2018-07-11 09:02:58 -0600,2018-07-11 09:11:37 -0600,174,"<<HKDevice: 0x2833fc0a0>, name:iPhone, manufac..."
2018-07-11 09:41:58-06:00,DistanceWalkingRunning,Marky Doug,11.4,km,2018-07-11 09:02:58 -0600,2018-07-11 09:11:37 -0600,0.13296,"<<HKDevice: 0x2833b9a40>, name:iPhone, manufac..."

In [18]:
us3 = records_list['2018-07-11 12':'2018-08-24 10']

In [19]:
us3.tail()

,activity_type,source,source_ver,unit_of_measure,activity_start_time,activity_end_time,value,device
creation_time,,,,,,,,
2018-08-24 09:51:59-06:00,DistanceWalkingRunning,Marky Doug,11.4.1,km,2018-08-24 08:06:06 -0600,2018-08-24 08:16:03 -0600,0.22755,"<<HKDevice: 0x283390730>, name:iPhone, manufac..."
2018-08-24 09:51:59-06:00,DistanceWalkingRunning,Marky Doug,11.4.1,km,2018-08-24 08:25:29 -0600,2018-08-24 08:35:27 -0600,0.34765,"<<HKDevice: 0x283390730>, name:iPhone, manufac..."
2018-08-24 09:51:59-06:00,DistanceWalkingRunning,Marky Doug,11.4.1,km,2018-08-24 09:17:19 -0600,2018-08-24 09:26:44 -0600,0.12697,"<<HKDevice: 0x283390730>, name:iPhone, manufac..."
2018-08-24 09:51:59-06:00,DistanceWalkingRunning,Marky Doug,11.4.1,km,2018-08-24 09:08:00 -0600,2018-08-24 09:17:19 -0600,0.07342,"<<HKDevice: 0x283390730>, name:iPhone, manufac..."
2018-08-24 09:51:59-06:00,DistanceWalkingRunning,Marky Doug,11.4.1,km,2018-08-24 08:16:03 -0600,2018-08-24 08:25:29 -0600,0.20783,"<<HKDevice: 0x283390730>, name:iPhone, manufac..."

In [20]:
china4 = records_list['2018-08-24 10':'2019-08-02 11']

In [21]:
china4.tail()

,activity_type,source,source_ver,unit_of_measure,activity_start_time,activity_end_time,value,device
creation_time,,,,,,,,
2019-08-02 09:52:18-06:00,StepCount,Marky Doug,12.3.1,count,2019-08-02 09:38:55 -0600,2019-08-02 09:45:52 -0600,302,"<<HKDevice: 0x2833a7a70>, name:iPhone, manufac..."
2019-08-02 10:13:40-06:00,DistanceWalkingRunning,Marky Doug,12.3.1,km,2019-08-02 09:53:06 -0600,2019-08-02 09:53:09 -0600,0.00656,"<<HKDevice: 0x2833bc870>, name:iPhone, manufac..."
2019-08-02 10:13:41-06:00,StepCount,Marky Doug,12.3.1,count,2019-08-02 09:53:06 -0600,2019-08-02 09:53:09 -0600,8,"<<HKDevice: 0x2833a7a70>, name:iPhone, manufac..."
2019-08-02 10:52:03-06:00,StepCount,Marky Doug,12.3.1,count,2019-08-02 10:25:30 -0600,2019-08-02 10:25:33 -0600,8,"<<HKDevice: 0x2833a7a70>, name:iPhone, manufac..."
2019-08-02 10:52:03-06:00,DistanceWalkingRunning,Marky Doug,12.3.1,km,2019-08-02 10:25:30 -0600,2019-08-02 10:25:33 -0600,0.00632,"<<HKDevice: 0x2833bc870>, name:iPhone, manufac..."

In [22]:
us4 = records_list['2019-08-02 11':'2019-08-16 02']

In [23]:
us4.tail()

,activity_type,source,source_ver,unit_of_measure,activity_start_time,activity_end_time,value,device
creation_time,,,,,,,,
2019-08-16 00:56:01-06:00,DistanceWalkingRunning,Marky Doug,12.4,km,2019-08-16 00:44:56 -0600,2019-08-16 00:46:59 -0600,0.11817,"<<HKDevice: 0x2833b9d10>, name:iPhone, manufac..."
2019-08-16 01:29:55-06:00,StepCount,Marky Doug,12.4,count,2019-08-16 01:19:26 -0600,2019-08-16 01:29:26 -0600,140,"<<HKDevice: 0x2833a1e00>, name:iPhone, manufac..."
2019-08-16 01:29:56-06:00,DistanceWalkingRunning,Marky Doug,12.4,km,2019-08-16 01:19:26 -0600,2019-08-16 01:29:26 -0600,0.10549,"<<HKDevice: 0x2833b9d10>, name:iPhone, manufac..."
2019-08-16 01:40:48-06:00,StepCount,Marky Doug,12.4,count,2019-08-16 01:29:26 -0600,2019-08-16 01:30:35 -0600,65,"<<HKDevice: 0x2833a1e00>, name:iPhone, manufac..."
2019-08-16 01:40:48-06:00,DistanceWalkingRunning,Marky Doug,12.4,km,2019-08-16 01:29:26 -0600,2019-08-16 01:30:35 -0600,0.04641,"<<HKDevice: 0x2833b9d10>, name:iPhone, manufac..."

In [24]:
china5 = records_list['2019-08-16 02':'2020-01-29 10']

In [25]:
china5.tail()

,activity_type,source,source_ver,unit_of_measure,activity_start_time,activity_end_time,value,device
creation_time,,,,,,,,
2020-01-29 08:23:17-06:00,DistanceWalkingRunning,Marky Doug,13.3,km,2020-01-29 08:12:42 -0600,2020-01-29 08:20:03 -0600,0.2395,"<<HKDevice: 0x2833b8140>, name:iPhone, manufac..."
2020-01-29 08:49:27-06:00,StepCount,Marky Doug,13.3,count,2020-01-29 08:49:23 -0600,2020-01-29 08:49:26 -0600,16,"<<HKDevice: 0x2833a1ef0>, name:iPhone, manufac..."
2020-01-29 08:51:31-06:00,StepCount,Marky Doug,13.3,count,2020-01-29 08:49:51 -0600,2020-01-29 08:49:54 -0600,8,"<<HKDevice: 0x2833a1ef0>, name:iPhone, manufac..."
2020-01-29 08:57:15-06:00,StepCount,Marky Doug,13.3,count,2020-01-29 08:57:08 -0600,2020-01-29 08:57:10 -0600,4,"<<HKDevice: 0x2833a1ef0>, name:iPhone, manufac..."
2020-01-29 09:00:11-06:00,DistanceWalkingRunning,Marky Doug,13.3,km,2020-01-29 08:49:23 -0600,2020-01-29 08:57:10 -0600,0.02236,"<<HKDevice: 0x2833b8140>, name:iPhone, manufac..."

In [26]:
us5 = records_list['2020-01-29 10':'2020-02-13 16']

In [27]:
us5.tail()

,activity_type,source,source_ver,unit_of_measure,activity_start_time,activity_end_time,value,device
creation_time,,,,,,,,
2020-02-13 15:19:03-06:00,HeadphoneAudioExposure,Marky Doug,13.3.1,dBASPL,2020-02-13 15:08:03 -0600,2020-02-13 15:38:00 -0600,64.5303,"<<HKDevice: 0x2833ac2d0>, name:AirPods, manufa..."
2020-02-13 15:49:00-06:00,HeadphoneAudioExposure,Marky Doug,13.3.1,dBASPL,2020-02-13 15:38:00 -0600,2020-02-13 16:07:56 -0600,63.8148,"<<HKDevice: 0x2833ac2d0>, name:AirPods, manufa..."
2020-02-13 16:18:57-06:00,HeadphoneAudioExposure,Marky Doug,13.3.1,dBASPL,2020-02-13 16:07:56 -0600,2020-02-13 16:37:53 -0600,73.1934,"<<HKDevice: 0x2833ac2d0>, name:AirPods, manufa..."
2020-02-13 16:48:53-06:00,HeadphoneAudioExposure,Marky Doug,13.3.1,dBASPL,2020-02-13 16:37:53 -0600,2020-02-13 16:46:10 -0600,75.8941,"<<HKDevice: 0x2833ac2d0>, name:AirPods, manufa..."
2020-02-13 16:57:37-06:00,HeadphoneAudioExposure,Marky Doug,13.3.1,dBASPL,2020-02-13 16:46:10 -0600,2020-02-13 17:03:49 -0600,75.4398,"<<HKDevice: 0x2833ac2d0>, name:AirPods, manufa..."

In [28]:
china6 = records_list['2020-02-13 17':'2022-03-02 15']

In [29]:
china6.head()

,activity_type,source,source_ver,unit_of_measure,activity_start_time,activity_end_time,value,device
creation_time,,,,,,,,
2020-02-13 17:15:16-06:00,HeadphoneAudioExposure,Marky Doug,13.3.1,dBASPL,2020-02-13 17:03:49 -0600,2020-02-13 17:12:15 -0600,75.4174,"<<HKDevice: 0x2833ac2d0>, name:AirPods, manufa..."
2020-02-13 17:23:42-06:00,HeadphoneAudioExposure,Marky Doug,13.3.1,dBASPL,2020-02-13 17:12:15 -0600,2020-02-13 17:23:35 -0600,75.3366,"<<HKDevice: 0x2833ac2d0>, name:AirPods, manufa..."
2020-02-13 17:35:05-06:00,HeadphoneAudioExposure,Marky Doug,13.3.1,dBASPL,2020-02-13 17:23:35 -0600,2020-02-13 17:52:13 -0600,75.8953,"<<HKDevice: 0x2833ac2d0>, name:AirPods, manufa..."
2020-02-13 17:36:26-06:00,DistanceWalkingRunning,Marky Doug,13.3.1,km,2020-02-13 17:25:58 -0600,2020-02-13 17:26:08 -0600,0.01801,"<<HKDevice: 0x2833bfbb0>, name:iPhone, manufac..."
2020-02-13 17:36:26-06:00,StepCount,Marky Doug,13.3.1,count,2020-02-13 17:25:58 -0600,2020-02-13 17:26:08 -0600,23,"<<HKDevice: 0x2833a1900>, name:iPhone, manufac..."

In [30]:
us6 = records_list['2022-03-02 16':]

In [31]:
us6.head()

,activity_type,source,source_ver,unit_of_measure,activity_start_time,activity_end_time,value,device
creation_time,,,,,,,,
2022-03-02 16:01:11-06:00,ActiveEnergyBurned,Mark的Apple Watch,8.4.2,Cal,2022-03-02 15:55:31 -0600,2022-03-02 15:55:41 -0600,0.327,"<<HKDevice: 0x283394d20>, name:Apple Watch, ma..."
2022-03-02 16:01:12-06:00,ActiveEnergyBurned,Mark的Apple Watch,8.4.2,Cal,2022-03-02 15:56:33 -0600,2022-03-02 15:57:03 -0600,0.306,"<<HKDevice: 0x283394d20>, name:Apple Watch, ma..."
2022-03-02 16:01:12-06:00,HeartRate,Mark的Apple Watch,8.4.2,count/min,2022-03-02 15:57:50 -0600,2022-03-02 15:57:50 -0600,78,"<<HKDevice: 0x283381f90>, name:Apple Watch, ma..."
2022-03-02 16:04:57-06:00,ActiveEnergyBurned,Mark的Apple Watch,8.4.2,Cal,2022-03-02 16:00:59 -0600,2022-03-02 16:02:01 -0600,0.412,"<<HKDevice: 0x283394d20>, name:Apple Watch, ma..."
2022-03-02 16:06:38-06:00,HeartRate,Mark的Apple Watch,8.4.2,count/min,2022-03-02 16:04:32 -0600,2022-03-02 16:04:32 -0600,84,"<<HKDevice: 0x283381f90>, name:Apple Watch, ma..."

In [32]:
china1 = change_time_zone(china1)
china2 = change_time_zone(china2)
china3 = change_time_zone(china3)
china4 = change_time_zone(china4)
china5 = change_time_zone(china5)
china6 = change_time_zone(china6)

In [35]:
time_zone_fixed = pd.concat([china1,us1,china2,us2,china3,us3,china4,us4,china5,us5,china6,us6])

In [36]:
time_zone_fixed

,activity_type,source,source_ver,unit_of_measure,activity_start_time,activity_end_time,value,device
creation_time,,,,,,,,
2015-10-10 20:27:26+08:00,DistanceWalkingRunning,Marky Doug,9.0.2,km,2015-10-10 18:48:17+08:00,2015-10-10 18:54:17+08:00,0.00144,"<<HKDevice: 0x2833bde00>, name:iPhone, manufac..."
2015-10-10 20:27:26+08:00,StepCount,Marky Doug,9.0.2,count,2015-10-10 16:46:48+08:00,2015-10-10 16:51:50+08:00,569.0,"<<HKDevice: 0x2833aa8a0>, name:iPhone, manufac..."
2015-10-10 20:27:26+08:00,StepCount,Marky Doug,9.0.2,count,2015-10-10 16:51:50+08:00,2015-10-10 16:54:35+08:00,135.0,"<<HKDevice: 0x2833aa8a0>, name:iPhone, manufac..."
2015-10-10 20:27:26+08:00,StepCount,Marky Doug,9.0.2,count,2015-10-10 17:09:06+08:00,2015-10-10 17:14:07+08:00,436.0,"<<HKDevice: 0x2833aa8a0>, name:iPhone, manufac..."
2015-10-10 20:27:26+08:00,StepCount,Marky Doug,9.0.2,count,2015-10-10 17:14:07+08:00,2015-10-10 17:19:07+08:00,569.0,"<<HKDevice: 0x2833aa8a0>, name:iPhone, manufac..."
...,...,...,...,...,...,...,...,...
2022-12-08 12:39:50-06:00,ActiveEnergyBurned,Mark的Apple Watch,9.1,Cal,2022-12-08 12:30:39 -0600,2022-12-08 12:30:49 -0600,0.076,"<<HKDevice: 0x2833b8e10>, name:Apple Watch, ma..."
2022-12-08 12:39:50-06:00,ActiveEnergyBurned,Mark的Apple Watch,9.1,Cal,2022-12-08 12:29:38 -0600,2022-12-08 12:30:39 -0600,1.673,"<<HKDevice: 0x2833b8e10>, name:Apple Watch, ma..."
2022-12-08 12:39:51-06:00,AppleExerciseTime,Mark的Apple Watch,9.1,min,2022-12-08 12:29:00 -0600,2022-12-08 12:30:00 -0600,1,"<<HKDevice: 0x2833b9fe0>, name:Apple Watch, ma..."
2022-12-08 12:40:35-06:00,ActiveEnergyBurned,Mark的Apple Watch,9.1,Cal,2022-12-08 12:39:53 -0600,2022-12-08 12:40:13 -0600,0.121,"<<HKDevice: 0x2833b8e10>, name:Apple Watch, ma..."
2022-12-08 12:40:35-06:00,ActiveEnergyBurned,Mark的Apple Watch,9.1,Cal,2022-12-08 12:38:51 -0600,2022-12-08 12:39:32 -0600,0.19,"<<HKDevice: 0x2833b8e10>, name:Apple Watch, ma..."

In [37]:
time_zone_fixed.to_csv('time_zone_fixed.csv')

In [39]:
time_zone_fixed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2267590 entries, 2015-10-10 20:27:26+08:00 to 2022-12-08 12:40:35-06:00
Data columns (total 8 columns):
 #   Column               Dtype
---  ------               -----
 0   activity_type        object
 1   source               object
 2   source_ver           object
 3   unit_of_measure      object
 4   activity_start_time  object
 5   activity_end_time    object
 6   value                object
 7   device               object
dtypes: object(8)
memory usage: 155.7+ MB